dist: trusty

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

language: java
jdk:
    - openjdk8
    - oraclejdk9

script:
    - jdk_switcher use oraclejdk9
    - ./gradlew :jdk9:compileJava
    - jdk_switcher use openjdk8
    - ./gradlew install --info -S -Psnapshot
    - jdk_switcher use $TRAVIS_JDK_VERSION
    - java -version
    - ./gradlew check --info -S

after_success: .ci/deploy.sh

branches:
    except:
        - gh-pages